server:
  port: 8081
  tomcat:
    threads:
      min-spare: 10
      max: 20
      #默认值 8192
    max-connections: 30
    #最大等待数 100
    accept-count: 10
    connection-timeout: 300

spring:
  datasource:
    username: root
    password: 123456
    #url?database?????????
    url: jdbc:mysql://182.254.221.168:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis?????
    host: 182.254.221.168
    # Redis??????
    port: 6378
    # ????????????0
    database: 0
    # ??????
    timeout: 1800000
    # ????
    password: jzj_redis
    lettuce:
      pool:
        # ?????????????????
        max-wait: -1
        # ???????????
        max-idle: 5
        # ???????????
        min-idle: 0
        # ??????????????????
        max-active: -1

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.entity

#showSql
logging:
  level:
    com.jzj.demo.mapper: debug



